---
general:
  buildTool: "mta"

stages:
  Build:
    mavenExecuteStaticCodeChecks: true 
    npmExecuteLint: true
    npmExecuteScripts: true 
  Additional Unit Tests:
    npmExecuteScripts: false  
  Acceptance:
    cloudFoundryDeploy: false  
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "0190f4c2trial"
    cfSpace: "dev"
    cfAppName: "app"
    cfCredentialsId: "deploy-to-cf"
    deployType: "standard"
    npmExecuteEndToEndTests: false 
  Compliance:
    sonarExecuteScan: false
  Release:
    cloudFoundryDeploy: true 
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "0190f4c2trial"
    cfSpace: "dev"
    cfAppName: "app"
    cfCredentialsId: "deploy-to-cf"
    deployType: "standard"
    tmsUpload: true  
steps:
  artifactPrepareVersion:
    versioningType: "cloud_noTag"
  npmExecuteLint:
    failOnError: false
  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"
  tmsUpload:
    nodeName: "qa"
    credentialsId: "tms-sk"